#[theme]
#primaryColor="#FF4B4B"
#backgroundColor="#FFFFFF"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#31333F"
#font="sans serif"

[theme]
primaryColor="#2e7be4"
backgroundColor="#9fc1ff"
secondaryBackgroundColor="#c5dcfd"
textColor="#0c26bd"
