#[theme]
#primaryColor="#FF4B4B"
#backgroundColor="#FFFFFF"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#31333F"
#font="sans serif"

[theme]
primaryColor="#88abc2"
backgroundColor="#ebf7f8"
secondaryBackgroundColor="#d0e0eb"
textColor="#49708a"
